language: java
matrix:
  include:
    - jdk: openjdk8
      env: GRADLE_PUBLISH=true
    - jdk: openjdk11
      env: GRADLE_PUBLISH=false
    - jdk: openjdk14
      env: GRADLE_PUBLISH=false
    - arch: arm64
      jdk: openjdk8
      env: GRADLE_PUBLISH=true
      before_install: sudo apt-get install openjdk-8-jdk
    - arch: arm64
      jdk: openjdk11
      env: GRADLE_PUBLISH=false
      before_install: sudo apt-get install openjdk-11-jdk
    - arch: arm64
      jdk: openjdk14
      env: GRADLE_PUBLISH=false
      before_install: sudo apt-get install openjdk-14-jdk
      
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: Hrc3t9ev/oGkIkeHk+vSYeqvIN5kW6mhtSLovvhyR3KV2TRBqjHdWW3c5MDgvetZu2s/DgUnQNtkHWrDpK+tXpT8gbJda+c2MkjmkZZH6hoVF2ASSWauDjBt8lbXcANDi2JJI3pMYxgK+H3Y9MgP1Sn+1FPdYm1MiUSpCT7Sxzc=
  - secure: PW/r0i02LqX8z/GAipforVN7Xj51F+H3oIzMxoJByM++CYp6Nx+EVym04+1rkHKVFbq7IXFdqe5pji3xrVsEilaB9jVDbmB2WdSmNxYvTHNTFtBmbmYMylc+hmV9pPh66JctyE9urq1q3x/e3stE1vVPHwqty8yDPCopsmlJRnc=
  - secure: FyNZfd3ML1DEgEfvORzVgBS3w8T7MKhcJVCuWJeAk+7oO4oVZdW9Es+xM1ylbZxpSQEDJlXopsjUXHaICYXGU3LvMsWtbm5LEJLBfLTVs0vlwZev2Us9KVChUf3JhjDmQVGOJL0+P+spjacN31xt3CL1qDkwSShvX2rX2RiRInw=
  - secure: Ak7IXZVWhEricCsiVH1Pbqjp8ywIvqB1FBxdQlZ+GkZzRekxa51BI9ZTLwuWfQvqJgmb+IXKWg7mvHu7DVFFCRRSb2C70C0CZICbIu2C9Xe5g15k4aFw/0vz+a7qVdvT+Q/ZlQ4vlxdcAt7Oh/MyUZ6f3+jO7w45v+8a04spmgY=
